version: "3"

services:
  backend:
    container_name: Q-n-A_backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/Q-n-A
    restart: always
    ports:
      - "9001:9001"
      - "9002:6060"
    depends_on:
      - mariadb

  frontend:
    container_name: Q-n-A_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - backend

  router:
    container_name: Q-n-A_router
    image: envoyproxy/envoy-alpine:v1.20-latest
    volumes:
      - ./router/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend

  mariadb:
    container_name: Q-n-A_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Q-n-A
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: Q-n-A_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "9003:80"
    depends_on:
      - mariadb

volumes:
  db: null
