// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"database/sql"
	"github.com/Q-n-A/Q-n-A/server/ping"
	"github.com/Q-n-A/Q-n-A/server/protobuf"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from server_wire.go:

func InjectServer(config *Config, db *sql.DB, logger *zap.Logger) (*Server, error) {
	store, err := newMySQLStore(db)
	if err != nil {
		return nil, err
	}
	echo := newEcho(store, logger)
	pingService := ping.NewPingService()
	server := newGRPCServer(logger, pingService)
	serverServer := newServer(echo, server, logger, config)
	return serverServer, nil
}

// server_wire.go:

var serverSet = wire.NewSet(ping.NewPingService, wire.Bind(new(protobuf.PingServer), new(*ping.PingService)), newMySQLStore,
	newEcho,
	newGRPCServer,

	newServer,
)
