// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/Q-n-A/Q-n-A/server/ping_impl"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InjectServer() (*Server, error) {
	pingService := ping_impl.NewPingService()
	server := NewServer(pingService)
	return server, nil
}

// wire.go:

var serverSet = wire.NewSet(ping_impl.NewPingService, NewServer)
