// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/Q-n-A/Q-n-A/server/ping"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InjectServer(logger *zap.Logger) (*Server, error) {
	pingService := ping.NewPingService()
	server := NewServer(logger, pingService)
	return server, nil
}

// wire.go:

var serverSet = wire.NewSet(ping.NewPingService, NewServer)
