// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/Q-n-A/Q-n-A/server"
	"github.com/Q-n-A/Q-n-A/server/ping"
	"github.com/Q-n-A/Q-n-A/server/protobuf"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func SetupServer(config *Config) (*server.Server, error) {
	v := _wireValue
	logger, err := zap.NewProduction(v...)
	if err != nil {
		return nil, err
	}
	serverConfig := provideServerConfig(config)
	pingService := ping.NewPingService()
	serverServer := server.NewServer(logger, serverConfig, pingService)
	return serverServer, nil
}

var (
	_wireValue = []zap.Option{}
)

// wire.go:

var serverSet = wire.NewSet(wire.Value([]zap.Option{}), zap.NewProduction, ping.NewPingService, wire.Bind(new(protobuf.PingServer), new(*ping.PingService)), provideServerConfig, server.NewServer)
